spring.application.name=student-management
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/studentdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=chedly
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


# Server configuration :
server.address=0.0.0.0
server.port=8089
server.servlet.context-path=/student
sonar.projectKey=jenkins
sonar.host.url=http://localhost:9000
sonar.token=0b904a13b24cefa464ac5df4639abe4d8e0c403a
sonar.java.binaries=target/classes
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
