spring.application.name=student-management

spring.datasource.url=jdbc:mariadb://mariadb:3306/studentdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

server.address=0.0.0.0
server.port=8080
server.servlet.context-path=/student
